server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springcloud_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/ # 入驻地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.enn.springcloud.entities